# Generated by Django 2.2.6 on 2019-10-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='profile_pic',
        ),
    ]
